name: Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*' # Executa apenas quando você cria uma tag no formato v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Configurar .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    # Step 3: Restaurar dependências
    - name: Restore dependencies
      run: dotnet restore

    # Step 4: Compilar o projeto
    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    # Step 5: Gerar o pacote NuGet
    - name: Pack NuGet package
      run: dotnet pack --configuration Release --no-build --output ./nupkg

    # Step 6: Publicar no NuGet
    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
